name: tweel_social_media
description: "A new Flutter project."
publish_to: "none"

version: 1.4.7+5

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.5
  http: ^1.2.0
  dropdown_button2: ^2.3.9
  shared_preferences: ^2.2.2
  multi_bloc_builder: ^1.0.0
  readmore: ^3.0.0
  wechat_assets_picker: ^9.0.0
  photo_manager: ^3.0.0
  dio: ^5.4.1
  flick_video_player: ^0.9.0
  video_player: ^2.8.3
  animate_do: ^4.2.0
  story_view: ^0.16.5
  flutter_staggered_grid_view: ^0.4.0
  autoscale_tabbarview: ^1.0.2
  colorful_safe_area: ^1.0.0
  hidable: ^1.0.6
  dotted_border: ^2.1.0
  flutter_animate: ^4.5.0
  visibility_detector: ^0.4.0+2
  provider: ^6.1.2
  path_provider: ^2.1.2
  get_thumbnail_video: ^0.7.3
  custom_refresh_indicator: ^4.0.1
  flutter_spinkit: ^5.2.1
  flutter_slidable: ^4.0.0
  hydrated_bloc: ^9.1.5
  emoji_picker_flutter: ^4.3.0
  cached_network_image: ^3.3.1
  web: ^1.1.1
  flutter_markdown: ^0.7.7+1
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^6.0.2
  socket_io_client: ^3.1.2
  grouped_list: ^6.0.0
  intl: ^0.20.2
  collection: ^1.18.0
  page_transition: ^2.1.0
  animations: ^2.0.11
  fluttertoast: ^8.2.12
  pull_to_refresh_flutter3: ^2.0.2

dependency_overrides:
  win32: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Coco-Gothic-Pro-Alt
      fonts:
        - asset: assets/fonts/Coco-Gothic-Pro-Alt-Variable-Roman-trial.ttf
    - family: Coco-Gothic-Pro
      fonts:
        - asset: assets/fonts/Coco-Gothic-Pro-Variable-Roman-trial.ttf
    - family: Ktweel
      fonts:
        - asset: assets/icons/Ktweel.ttf
