// Flutter icons Ktweel
// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
// This font was generated by FlutterIcon.com, which is derived from Fontello.
//
// To use this font, place it in your fonts/ directory and include the
// following in your pubspec.yaml
//
// flutter:
//   fonts:
//    - family:  Ktweel
//      fonts:
//       - asset: fonts/Ktweel.ttf
//
// 
//
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class Ktweel {
  Ktweel._();

  static const _kFontFam = 'Ktweel';
  static const String? _kFontPkg = null;

  static const IconData about = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_circle = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_bottom_outlined = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_circle_down = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_circle_left = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_circle_right = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_circle_up = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down_circle = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down_ios = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left_circle = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left_ios = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left_outlined = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_circle = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_ios = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_outlined = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up_circle = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up_ios = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up_outlined = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backward = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard_close = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard_tick = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_circle = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData danger = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard_2 = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard_3 = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dislike = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_2 = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_3 = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_4 = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_slash = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData global = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gps = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_2 = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circle = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_rugged = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout_2 = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_text = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microphone = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_notif = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microphone_mute = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus_cirlce = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_circle = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_horiz_2 = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_horiz = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_vert_2 = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_vert = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_bing = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause_circle = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_circle = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_square = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_circle = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_delete = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redo = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remove = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remove_2 = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_2 = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_3 = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send_2 = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_cross = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_2 = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_tick = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stats = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData status = IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData status_2 = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_file = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick_circle = IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick_circle_1 = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick_square = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unbookmark = IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo = IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_edit = IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_remove = IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verify = IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_high = IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_mute = IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi_square = IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
